<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PostSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('posts')->insert([
            'title' => 'This is just a dummy title 1',
            'slug' => 'this-is-just-a-dummy-title-1',
            'category_id' => 1,
            'image'=>'https://source.unsplash.com/random/1920x1080',
            'excerpt'=>"This is just some sample data written here to fill the space...",
            'content'=>'<div id="lipsum">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer aliquet maximus odio. Curabitur vel massa eros. Nullam efficitur vestibulum eros, eu egestas diam tempor vitae. Maecenas ac auctor sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In porta, velit sit amet faucibus bibendum, massa dolor semper lorem, ut posuere nunc lacus ut nisi. Nam nisl lorem, iaculis eu odio id, aliquet facilisis arcu.</p>
            <p>Nullam a mauris turpis. Etiam faucibus est vel metus interdum lobortis finibus ornare erat. Nam vehicula quam mi, porta sagittis ligula malesuada sed. Nulla finibus scelerisque neque cursus laoreet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dapibus enim sed euismod ullamcorper. Duis at vulputate tellus. Proin ac purus eget ligula congue fermentum a in orci. Quisque fermentum elit at purus luctus, at pellentesque risus tincidunt. Nulla tincidunt nec est at consequat. Nullam nec dignissim leo. Maecenas condimentum et lorem eget viverra. Suspendisse pellentesque dui et massa aliquet, sed auctor dolor scelerisque. Morbi feugiat arcu a lacus rutrum posuere. Cras iaculis aliquet auctor. Nunc sagittis massa eget facilisis ullamcorper.</p>
            <p><strong>Nulla fermentum ex dui, vel aliquet mi auctor quis. Pellentesque cursus, nibh eu dapibus pulvinar, mi enim pellentesque elit, vel venenatis lacus metus et mi. Cras aliquam eu risus quis efficitur. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas congue eu urna vitae consectetur. Etiam sed risus auctor, porttitor ligula nec, auctor neque. Vivamus facilisis non dui nec ultrices. Curabitur magna sem, dignissim id dolor vel, tempor interdum erat. Maecenas et massa ut metus dictum cursus. Fusce mi tellus, viverra non nibh eleifend, elementum gravida eros. Etiam efficitur nulla a justo facilisis, non molestie tortor lobortis. Vestibulum aliquam mi in dolor pellentesque semper ac ac quam. Cras euismod egestas est, nec mattis metus fringilla quis. Curabitur aliquet libero non varius aliquam.</strong></p>
            <p><em>Quisque id erat vel enim scelerisque rutrum. Morbi vel nibh scelerisque, porta erat vel, sagittis risus. Vestibulum non malesuada ex, nec maximus libero. Nulla ut elementum mi. Nunc egestas vestibulum porta. Nam nisi enim, aliquam vel odio id, mollis suscipit mauris. Donec viverra congue sollicitudin. Duis euismod augue non erat vehicula, et ultricies mi malesuada. Morbi congue maximus velit. Praesent iaculis tempus purus vitae congue. Nullam sit amet volutpat sem, consectetur aliquam erat. Proin pellentesque lorem eget odio dapibus iaculis. Etiam tellus tortor, dignissim iaculis finibus vitae, luctus ut ante. Maecenas tempor non dolor a tincidunt. Sed varius condimentum lacus, id dignissim est congue a. Nulla rutrum, mi sit amet venenatis cursus, urna quam pellentesque metus, a tristique mauris odio a lorem.</em></p>
            <p><span style="background-color: #f1c40f;">Maecenas consectetur tellus eget imperdiet sagittis. Quisque erat magna, molestie sed semper id, auctor vel turpis. Donec luctus odio justo, vel rhoncus lorem elementum et. Maecenas placerat congue malesuada. Fusce efficitur quis orci ut semper. Donec vulputate nulla urna, non porta massa ullamcorper sit amet. Aenean vel dictum augue, sit amet fermentum lorem. Quisque felis felis, dapibus non fermentum in, fermentum ac sapien. Nulla facilisi. Nulla quam ante, scelerisque eu urna sit amet, fermentum pulvinar orci. Vestibulum pharetra leo orci, eu vehicula risus pellentesque vitae. Donec molestie tempus interdum. Pellentesque posuere dolor eu libero tempus suscipit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</span></p>
            </div>',
        ]);

        DB::table('posts')->insert([
            'title' => 'This is just a dummy title-2',
            'slug' => 'this-is-just-a-dummy-title-2',
            'category_id' => 1,
            'image'=>'https://source.unsplash.com/random/1920x1080',
            'excerpt'=>"This is just some sample data written here to fill the space...",
            'content'=>'<div id="lipsum">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer aliquet maximus odio. Curabitur vel massa eros. Nullam efficitur vestibulum eros, eu egestas diam tempor vitae. Maecenas ac auctor sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In porta, velit sit amet faucibus bibendum, massa dolor semper lorem, ut posuere nunc lacus ut nisi. Nam nisl lorem, iaculis eu odio id, aliquet facilisis arcu.</p>
            <p>Nullam a mauris turpis. Etiam faucibus est vel metus interdum lobortis finibus ornare erat. Nam vehicula quam mi, porta sagittis ligula malesuada sed. Nulla finibus scelerisque neque cursus laoreet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dapibus enim sed euismod ullamcorper. Duis at vulputate tellus. Proin ac purus eget ligula congue fermentum a in orci. Quisque fermentum elit at purus luctus, at pellentesque risus tincidunt. Nulla tincidunt nec est at consequat. Nullam nec dignissim leo. Maecenas condimentum et lorem eget viverra. Suspendisse pellentesque dui et massa aliquet, sed auctor dolor scelerisque. Morbi feugiat arcu a lacus rutrum posuere. Cras iaculis aliquet auctor. Nunc sagittis massa eget facilisis ullamcorper.</p>
            <p><strong>Nulla fermentum ex dui, vel aliquet mi auctor quis. Pellentesque cursus, nibh eu dapibus pulvinar, mi enim pellentesque elit, vel venenatis lacus metus et mi. Cras aliquam eu risus quis efficitur. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas congue eu urna vitae consectetur. Etiam sed risus auctor, porttitor ligula nec, auctor neque. Vivamus facilisis non dui nec ultrices. Curabitur magna sem, dignissim id dolor vel, tempor interdum erat. Maecenas et massa ut metus dictum cursus. Fusce mi tellus, viverra non nibh eleifend, elementum gravida eros. Etiam efficitur nulla a justo facilisis, non molestie tortor lobortis. Vestibulum aliquam mi in dolor pellentesque semper ac ac quam. Cras euismod egestas est, nec mattis metus fringilla quis. Curabitur aliquet libero non varius aliquam.</strong></p>
            <p><em>Quisque id erat vel enim scelerisque rutrum. Morbi vel nibh scelerisque, porta erat vel, sagittis risus. Vestibulum non malesuada ex, nec maximus libero. Nulla ut elementum mi. Nunc egestas vestibulum porta. Nam nisi enim, aliquam vel odio id, mollis suscipit mauris. Donec viverra congue sollicitudin. Duis euismod augue non erat vehicula, et ultricies mi malesuada. Morbi congue maximus velit. Praesent iaculis tempus purus vitae congue. Nullam sit amet volutpat sem, consectetur aliquam erat. Proin pellentesque lorem eget odio dapibus iaculis. Etiam tellus tortor, dignissim iaculis finibus vitae, luctus ut ante. Maecenas tempor non dolor a tincidunt. Sed varius condimentum lacus, id dignissim est congue a. Nulla rutrum, mi sit amet venenatis cursus, urna quam pellentesque metus, a tristique mauris odio a lorem.</em></p>
            <p><span style="background-color: #f1c40f;">Maecenas consectetur tellus eget imperdiet sagittis. Quisque erat magna, molestie sed semper id, auctor vel turpis. Donec luctus odio justo, vel rhoncus lorem elementum et. Maecenas placerat congue malesuada. Fusce efficitur quis orci ut semper. Donec vulputate nulla urna, non porta massa ullamcorper sit amet. Aenean vel dictum augue, sit amet fermentum lorem. Quisque felis felis, dapibus non fermentum in, fermentum ac sapien. Nulla facilisi. Nulla quam ante, scelerisque eu urna sit amet, fermentum pulvinar orci. Vestibulum pharetra leo orci, eu vehicula risus pellentesque vitae. Donec molestie tempus interdum. Pellentesque posuere dolor eu libero tempus suscipit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</span></p>
            </div>',
        ]);

        DB::table('posts')->insert([
            'title' => 'This is just a dummy title-3',
            'slug' => 'this-is-just-a-dummy-title-3',
            'category_id' => 2,
            'image'=>'https://source.unsplash.com/random/1920x1080',
            'excerpt'=>"This is just some sample data written here to fill the space...",
            'content'=>'<div id="lipsum">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer aliquet maximus odio. Curabitur vel massa eros. Nullam efficitur vestibulum eros, eu egestas diam tempor vitae. Maecenas ac auctor sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In porta, velit sit amet faucibus bibendum, massa dolor semper lorem, ut posuere nunc lacus ut nisi. Nam nisl lorem, iaculis eu odio id, aliquet facilisis arcu.</p>
            <p>Nullam a mauris turpis. Etiam faucibus est vel metus interdum lobortis finibus ornare erat. Nam vehicula quam mi, porta sagittis ligula malesuada sed. Nulla finibus scelerisque neque cursus laoreet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dapibus enim sed euismod ullamcorper. Duis at vulputate tellus. Proin ac purus eget ligula congue fermentum a in orci. Quisque fermentum elit at purus luctus, at pellentesque risus tincidunt. Nulla tincidunt nec est at consequat. Nullam nec dignissim leo. Maecenas condimentum et lorem eget viverra. Suspendisse pellentesque dui et massa aliquet, sed auctor dolor scelerisque. Morbi feugiat arcu a lacus rutrum posuere. Cras iaculis aliquet auctor. Nunc sagittis massa eget facilisis ullamcorper.</p>
            <p><strong>Nulla fermentum ex dui, vel aliquet mi auctor quis. Pellentesque cursus, nibh eu dapibus pulvinar, mi enim pellentesque elit, vel venenatis lacus metus et mi. Cras aliquam eu risus quis efficitur. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas congue eu urna vitae consectetur. Etiam sed risus auctor, porttitor ligula nec, auctor neque. Vivamus facilisis non dui nec ultrices. Curabitur magna sem, dignissim id dolor vel, tempor interdum erat. Maecenas et massa ut metus dictum cursus. Fusce mi tellus, viverra non nibh eleifend, elementum gravida eros. Etiam efficitur nulla a justo facilisis, non molestie tortor lobortis. Vestibulum aliquam mi in dolor pellentesque semper ac ac quam. Cras euismod egestas est, nec mattis metus fringilla quis. Curabitur aliquet libero non varius aliquam.</strong></p>
            <p><em>Quisque id erat vel enim scelerisque rutrum. Morbi vel nibh scelerisque, porta erat vel, sagittis risus. Vestibulum non malesuada ex, nec maximus libero. Nulla ut elementum mi. Nunc egestas vestibulum porta. Nam nisi enim, aliquam vel odio id, mollis suscipit mauris. Donec viverra congue sollicitudin. Duis euismod augue non erat vehicula, et ultricies mi malesuada. Morbi congue maximus velit. Praesent iaculis tempus purus vitae congue. Nullam sit amet volutpat sem, consectetur aliquam erat. Proin pellentesque lorem eget odio dapibus iaculis. Etiam tellus tortor, dignissim iaculis finibus vitae, luctus ut ante. Maecenas tempor non dolor a tincidunt. Sed varius condimentum lacus, id dignissim est congue a. Nulla rutrum, mi sit amet venenatis cursus, urna quam pellentesque metus, a tristique mauris odio a lorem.</em></p>
            <p><span style="background-color: #f1c40f;">Maecenas consectetur tellus eget imperdiet sagittis. Quisque erat magna, molestie sed semper id, auctor vel turpis. Donec luctus odio justo, vel rhoncus lorem elementum et. Maecenas placerat congue malesuada. Fusce efficitur quis orci ut semper. Donec vulputate nulla urna, non porta massa ullamcorper sit amet. Aenean vel dictum augue, sit amet fermentum lorem. Quisque felis felis, dapibus non fermentum in, fermentum ac sapien. Nulla facilisi. Nulla quam ante, scelerisque eu urna sit amet, fermentum pulvinar orci. Vestibulum pharetra leo orci, eu vehicula risus pellentesque vitae. Donec molestie tempus interdum. Pellentesque posuere dolor eu libero tempus suscipit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</span></p>
            </div>',
        ]);

        DB::table('posts')->insert([
            'title' => 'This is just a dummy title-4',
            'slug' => 'this-is-just-a-dummy-title-4',
            'category_id' => 2,
            'image'=>'https://source.unsplash.com/random/1920x1080',
            'excerpt'=>"This is just some sample data written here to fill the space...",
            'content'=>'<div id="lipsum">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer aliquet maximus odio. Curabitur vel massa eros. Nullam efficitur vestibulum eros, eu egestas diam tempor vitae. Maecenas ac auctor sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In porta, velit sit amet faucibus bibendum, massa dolor semper lorem, ut posuere nunc lacus ut nisi. Nam nisl lorem, iaculis eu odio id, aliquet facilisis arcu.</p>
            <p>Nullam a mauris turpis. Etiam faucibus est vel metus interdum lobortis finibus ornare erat. Nam vehicula quam mi, porta sagittis ligula malesuada sed. Nulla finibus scelerisque neque cursus laoreet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dapibus enim sed euismod ullamcorper. Duis at vulputate tellus. Proin ac purus eget ligula congue fermentum a in orci. Quisque fermentum elit at purus luctus, at pellentesque risus tincidunt. Nulla tincidunt nec est at consequat. Nullam nec dignissim leo. Maecenas condimentum et lorem eget viverra. Suspendisse pellentesque dui et massa aliquet, sed auctor dolor scelerisque. Morbi feugiat arcu a lacus rutrum posuere. Cras iaculis aliquet auctor. Nunc sagittis massa eget facilisis ullamcorper.</p>
            <p><strong>Nulla fermentum ex dui, vel aliquet mi auctor quis. Pellentesque cursus, nibh eu dapibus pulvinar, mi enim pellentesque elit, vel venenatis lacus metus et mi. Cras aliquam eu risus quis efficitur. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas congue eu urna vitae consectetur. Etiam sed risus auctor, porttitor ligula nec, auctor neque. Vivamus facilisis non dui nec ultrices. Curabitur magna sem, dignissim id dolor vel, tempor interdum erat. Maecenas et massa ut metus dictum cursus. Fusce mi tellus, viverra non nibh eleifend, elementum gravida eros. Etiam efficitur nulla a justo facilisis, non molestie tortor lobortis. Vestibulum aliquam mi in dolor pellentesque semper ac ac quam. Cras euismod egestas est, nec mattis metus fringilla quis. Curabitur aliquet libero non varius aliquam.</strong></p>
            <p><em>Quisque id erat vel enim scelerisque rutrum. Morbi vel nibh scelerisque, porta erat vel, sagittis risus. Vestibulum non malesuada ex, nec maximus libero. Nulla ut elementum mi. Nunc egestas vestibulum porta. Nam nisi enim, aliquam vel odio id, mollis suscipit mauris. Donec viverra congue sollicitudin. Duis euismod augue non erat vehicula, et ultricies mi malesuada. Morbi congue maximus velit. Praesent iaculis tempus purus vitae congue. Nullam sit amet volutpat sem, consectetur aliquam erat. Proin pellentesque lorem eget odio dapibus iaculis. Etiam tellus tortor, dignissim iaculis finibus vitae, luctus ut ante. Maecenas tempor non dolor a tincidunt. Sed varius condimentum lacus, id dignissim est congue a. Nulla rutrum, mi sit amet venenatis cursus, urna quam pellentesque metus, a tristique mauris odio a lorem.</em></p>
            <p><span style="background-color: #f1c40f;">Maecenas consectetur tellus eget imperdiet sagittis. Quisque erat magna, molestie sed semper id, auctor vel turpis. Donec luctus odio justo, vel rhoncus lorem elementum et. Maecenas placerat congue malesuada. Fusce efficitur quis orci ut semper. Donec vulputate nulla urna, non porta massa ullamcorper sit amet. Aenean vel dictum augue, sit amet fermentum lorem. Quisque felis felis, dapibus non fermentum in, fermentum ac sapien. Nulla facilisi. Nulla quam ante, scelerisque eu urna sit amet, fermentum pulvinar orci. Vestibulum pharetra leo orci, eu vehicula risus pellentesque vitae. Donec molestie tempus interdum. Pellentesque posuere dolor eu libero tempus suscipit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</span></p>
            </div>',
        ]);

        DB::table('posts')->insert([
            'title' => 'This is just a dummy title-5',
            'slug' => 'this-is-just-a-dummy-title-5',
            'category_id' => 3,
            'image'=>'https://source.unsplash.com/random/1920x1080',
            'excerpt'=>"This is just some sample data written here to fill the space...",
            'content'=>'<div id="lipsum">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer aliquet maximus odio. Curabitur vel massa eros. Nullam efficitur vestibulum eros, eu egestas diam tempor vitae. Maecenas ac auctor sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In porta, velit sit amet faucibus bibendum, massa dolor semper lorem, ut posuere nunc lacus ut nisi. Nam nisl lorem, iaculis eu odio id, aliquet facilisis arcu.</p>
            <p>Nullam a mauris turpis. Etiam faucibus est vel metus interdum lobortis finibus ornare erat. Nam vehicula quam mi, porta sagittis ligula malesuada sed. Nulla finibus scelerisque neque cursus laoreet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dapibus enim sed euismod ullamcorper. Duis at vulputate tellus. Proin ac purus eget ligula congue fermentum a in orci. Quisque fermentum elit at purus luctus, at pellentesque risus tincidunt. Nulla tincidunt nec est at consequat. Nullam nec dignissim leo. Maecenas condimentum et lorem eget viverra. Suspendisse pellentesque dui et massa aliquet, sed auctor dolor scelerisque. Morbi feugiat arcu a lacus rutrum posuere. Cras iaculis aliquet auctor. Nunc sagittis massa eget facilisis ullamcorper.</p>
            <p><strong>Nulla fermentum ex dui, vel aliquet mi auctor quis. Pellentesque cursus, nibh eu dapibus pulvinar, mi enim pellentesque elit, vel venenatis lacus metus et mi. Cras aliquam eu risus quis efficitur. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas congue eu urna vitae consectetur. Etiam sed risus auctor, porttitor ligula nec, auctor neque. Vivamus facilisis non dui nec ultrices. Curabitur magna sem, dignissim id dolor vel, tempor interdum erat. Maecenas et massa ut metus dictum cursus. Fusce mi tellus, viverra non nibh eleifend, elementum gravida eros. Etiam efficitur nulla a justo facilisis, non molestie tortor lobortis. Vestibulum aliquam mi in dolor pellentesque semper ac ac quam. Cras euismod egestas est, nec mattis metus fringilla quis. Curabitur aliquet libero non varius aliquam.</strong></p>
            <p><em>Quisque id erat vel enim scelerisque rutrum. Morbi vel nibh scelerisque, porta erat vel, sagittis risus. Vestibulum non malesuada ex, nec maximus libero. Nulla ut elementum mi. Nunc egestas vestibulum porta. Nam nisi enim, aliquam vel odio id, mollis suscipit mauris. Donec viverra congue sollicitudin. Duis euismod augue non erat vehicula, et ultricies mi malesuada. Morbi congue maximus velit. Praesent iaculis tempus purus vitae congue. Nullam sit amet volutpat sem, consectetur aliquam erat. Proin pellentesque lorem eget odio dapibus iaculis. Etiam tellus tortor, dignissim iaculis finibus vitae, luctus ut ante. Maecenas tempor non dolor a tincidunt. Sed varius condimentum lacus, id dignissim est congue a. Nulla rutrum, mi sit amet venenatis cursus, urna quam pellentesque metus, a tristique mauris odio a lorem.</em></p>
            <p><span style="background-color: #f1c40f;">Maecenas consectetur tellus eget imperdiet sagittis. Quisque erat magna, molestie sed semper id, auctor vel turpis. Donec luctus odio justo, vel rhoncus lorem elementum et. Maecenas placerat congue malesuada. Fusce efficitur quis orci ut semper. Donec vulputate nulla urna, non porta massa ullamcorper sit amet. Aenean vel dictum augue, sit amet fermentum lorem. Quisque felis felis, dapibus non fermentum in, fermentum ac sapien. Nulla facilisi. Nulla quam ante, scelerisque eu urna sit amet, fermentum pulvinar orci. Vestibulum pharetra leo orci, eu vehicula risus pellentesque vitae. Donec molestie tempus interdum. Pellentesque posuere dolor eu libero tempus suscipit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</span></p>
            </div>',
        ]);

        DB::table('posts')->insert([
            'title' => 'This is just a dummy title-6',
            'slug' => 'this-is-just-a-dummy-title-6',
            'category_id' => 4,
            'image'=>'https://source.unsplash.com/random/1920x1080',
            'excerpt'=>"This is just some sample data written here to fill the space...",
            'content'=>'<div id="lipsum">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer aliquet maximus odio. Curabitur vel massa eros. Nullam efficitur vestibulum eros, eu egestas diam tempor vitae. Maecenas ac auctor sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In porta, velit sit amet faucibus bibendum, massa dolor semper lorem, ut posuere nunc lacus ut nisi. Nam nisl lorem, iaculis eu odio id, aliquet facilisis arcu.</p>
            <p>Nullam a mauris turpis. Etiam faucibus est vel metus interdum lobortis finibus ornare erat. Nam vehicula quam mi, porta sagittis ligula malesuada sed. Nulla finibus scelerisque neque cursus laoreet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dapibus enim sed euismod ullamcorper. Duis at vulputate tellus. Proin ac purus eget ligula congue fermentum a in orci. Quisque fermentum elit at purus luctus, at pellentesque risus tincidunt. Nulla tincidunt nec est at consequat. Nullam nec dignissim leo. Maecenas condimentum et lorem eget viverra. Suspendisse pellentesque dui et massa aliquet, sed auctor dolor scelerisque. Morbi feugiat arcu a lacus rutrum posuere. Cras iaculis aliquet auctor. Nunc sagittis massa eget facilisis ullamcorper.</p>
            <p><strong>Nulla fermentum ex dui, vel aliquet mi auctor quis. Pellentesque cursus, nibh eu dapibus pulvinar, mi enim pellentesque elit, vel venenatis lacus metus et mi. Cras aliquam eu risus quis efficitur. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas congue eu urna vitae consectetur. Etiam sed risus auctor, porttitor ligula nec, auctor neque. Vivamus facilisis non dui nec ultrices. Curabitur magna sem, dignissim id dolor vel, tempor interdum erat. Maecenas et massa ut metus dictum cursus. Fusce mi tellus, viverra non nibh eleifend, elementum gravida eros. Etiam efficitur nulla a justo facilisis, non molestie tortor lobortis. Vestibulum aliquam mi in dolor pellentesque semper ac ac quam. Cras euismod egestas est, nec mattis metus fringilla quis. Curabitur aliquet libero non varius aliquam.</strong></p>
            <p><em>Quisque id erat vel enim scelerisque rutrum. Morbi vel nibh scelerisque, porta erat vel, sagittis risus. Vestibulum non malesuada ex, nec maximus libero. Nulla ut elementum mi. Nunc egestas vestibulum porta. Nam nisi enim, aliquam vel odio id, mollis suscipit mauris. Donec viverra congue sollicitudin. Duis euismod augue non erat vehicula, et ultricies mi malesuada. Morbi congue maximus velit. Praesent iaculis tempus purus vitae congue. Nullam sit amet volutpat sem, consectetur aliquam erat. Proin pellentesque lorem eget odio dapibus iaculis. Etiam tellus tortor, dignissim iaculis finibus vitae, luctus ut ante. Maecenas tempor non dolor a tincidunt. Sed varius condimentum lacus, id dignissim est congue a. Nulla rutrum, mi sit amet venenatis cursus, urna quam pellentesque metus, a tristique mauris odio a lorem.</em></p>
            <p><span style="background-color: #f1c40f;">Maecenas consectetur tellus eget imperdiet sagittis. Quisque erat magna, molestie sed semper id, auctor vel turpis. Donec luctus odio justo, vel rhoncus lorem elementum et. Maecenas placerat congue malesuada. Fusce efficitur quis orci ut semper. Donec vulputate nulla urna, non porta massa ullamcorper sit amet. Aenean vel dictum augue, sit amet fermentum lorem. Quisque felis felis, dapibus non fermentum in, fermentum ac sapien. Nulla facilisi. Nulla quam ante, scelerisque eu urna sit amet, fermentum pulvinar orci. Vestibulum pharetra leo orci, eu vehicula risus pellentesque vitae. Donec molestie tempus interdum. Pellentesque posuere dolor eu libero tempus suscipit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</span></p>
            </div>',
        ]);

        DB::table('posts')->insert([
            'title' => 'This is just a dummy title-7',
            'slug' => 'this-is-just-a-dummy-title-7',
            'category_id' => 4,
            'image'=>'https://source.unsplash.com/random/1920x1080',
            'excerpt'=>"This is just some sample data written here to fill the space...",
            'content'=>'<div id="lipsum">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer aliquet maximus odio. Curabitur vel massa eros. Nullam efficitur vestibulum eros, eu egestas diam tempor vitae. Maecenas ac auctor sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In porta, velit sit amet faucibus bibendum, massa dolor semper lorem, ut posuere nunc lacus ut nisi. Nam nisl lorem, iaculis eu odio id, aliquet facilisis arcu.</p>
            <p>Nullam a mauris turpis. Etiam faucibus est vel metus interdum lobortis finibus ornare erat. Nam vehicula quam mi, porta sagittis ligula malesuada sed. Nulla finibus scelerisque neque cursus laoreet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dapibus enim sed euismod ullamcorper. Duis at vulputate tellus. Proin ac purus eget ligula congue fermentum a in orci. Quisque fermentum elit at purus luctus, at pellentesque risus tincidunt. Nulla tincidunt nec est at consequat. Nullam nec dignissim leo. Maecenas condimentum et lorem eget viverra. Suspendisse pellentesque dui et massa aliquet, sed auctor dolor scelerisque. Morbi feugiat arcu a lacus rutrum posuere. Cras iaculis aliquet auctor. Nunc sagittis massa eget facilisis ullamcorper.</p>
            <p><strong>Nulla fermentum ex dui, vel aliquet mi auctor quis. Pellentesque cursus, nibh eu dapibus pulvinar, mi enim pellentesque elit, vel venenatis lacus metus et mi. Cras aliquam eu risus quis efficitur. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas congue eu urna vitae consectetur. Etiam sed risus auctor, porttitor ligula nec, auctor neque. Vivamus facilisis non dui nec ultrices. Curabitur magna sem, dignissim id dolor vel, tempor interdum erat. Maecenas et massa ut metus dictum cursus. Fusce mi tellus, viverra non nibh eleifend, elementum gravida eros. Etiam efficitur nulla a justo facilisis, non molestie tortor lobortis. Vestibulum aliquam mi in dolor pellentesque semper ac ac quam. Cras euismod egestas est, nec mattis metus fringilla quis. Curabitur aliquet libero non varius aliquam.</strong></p>
            <p><em>Quisque id erat vel enim scelerisque rutrum. Morbi vel nibh scelerisque, porta erat vel, sagittis risus. Vestibulum non malesuada ex, nec maximus libero. Nulla ut elementum mi. Nunc egestas vestibulum porta. Nam nisi enim, aliquam vel odio id, mollis suscipit mauris. Donec viverra congue sollicitudin. Duis euismod augue non erat vehicula, et ultricies mi malesuada. Morbi congue maximus velit. Praesent iaculis tempus purus vitae congue. Nullam sit amet volutpat sem, consectetur aliquam erat. Proin pellentesque lorem eget odio dapibus iaculis. Etiam tellus tortor, dignissim iaculis finibus vitae, luctus ut ante. Maecenas tempor non dolor a tincidunt. Sed varius condimentum lacus, id dignissim est congue a. Nulla rutrum, mi sit amet venenatis cursus, urna quam pellentesque metus, a tristique mauris odio a lorem.</em></p>
            <p><span style="background-color: #f1c40f;">Maecenas consectetur tellus eget imperdiet sagittis. Quisque erat magna, molestie sed semper id, auctor vel turpis. Donec luctus odio justo, vel rhoncus lorem elementum et. Maecenas placerat congue malesuada. Fusce efficitur quis orci ut semper. Donec vulputate nulla urna, non porta massa ullamcorper sit amet. Aenean vel dictum augue, sit amet fermentum lorem. Quisque felis felis, dapibus non fermentum in, fermentum ac sapien. Nulla facilisi. Nulla quam ante, scelerisque eu urna sit amet, fermentum pulvinar orci. Vestibulum pharetra leo orci, eu vehicula risus pellentesque vitae. Donec molestie tempus interdum. Pellentesque posuere dolor eu libero tempus suscipit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</span></p>
            </div>',
        ]);

        DB::table('posts')->insert([
            'title' => 'This is just a dummy title-8',
            'slug' => 'this-is-just-a-dummy-title-8',
            'category_id' => 4,
            'image'=>'https://source.unsplash.com/random/1920x1080',
            'excerpt'=>"This is just some sample data written here to fill the space...",
            'content'=>'<div id="lipsum">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer aliquet maximus odio. Curabitur vel massa eros. Nullam efficitur vestibulum eros, eu egestas diam tempor vitae. Maecenas ac auctor sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In porta, velit sit amet faucibus bibendum, massa dolor semper lorem, ut posuere nunc lacus ut nisi. Nam nisl lorem, iaculis eu odio id, aliquet facilisis arcu.</p>
            <p>Nullam a mauris turpis. Etiam faucibus est vel metus interdum lobortis finibus ornare erat. Nam vehicula quam mi, porta sagittis ligula malesuada sed. Nulla finibus scelerisque neque cursus laoreet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dapibus enim sed euismod ullamcorper. Duis at vulputate tellus. Proin ac purus eget ligula congue fermentum a in orci. Quisque fermentum elit at purus luctus, at pellentesque risus tincidunt. Nulla tincidunt nec est at consequat. Nullam nec dignissim leo. Maecenas condimentum et lorem eget viverra. Suspendisse pellentesque dui et massa aliquet, sed auctor dolor scelerisque. Morbi feugiat arcu a lacus rutrum posuere. Cras iaculis aliquet auctor. Nunc sagittis massa eget facilisis ullamcorper.</p>
            <p><strong>Nulla fermentum ex dui, vel aliquet mi auctor quis. Pellentesque cursus, nibh eu dapibus pulvinar, mi enim pellentesque elit, vel venenatis lacus metus et mi. Cras aliquam eu risus quis efficitur. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas congue eu urna vitae consectetur. Etiam sed risus auctor, porttitor ligula nec, auctor neque. Vivamus facilisis non dui nec ultrices. Curabitur magna sem, dignissim id dolor vel, tempor interdum erat. Maecenas et massa ut metus dictum cursus. Fusce mi tellus, viverra non nibh eleifend, elementum gravida eros. Etiam efficitur nulla a justo facilisis, non molestie tortor lobortis. Vestibulum aliquam mi in dolor pellentesque semper ac ac quam. Cras euismod egestas est, nec mattis metus fringilla quis. Curabitur aliquet libero non varius aliquam.</strong></p>
            <p><em>Quisque id erat vel enim scelerisque rutrum. Morbi vel nibh scelerisque, porta erat vel, sagittis risus. Vestibulum non malesuada ex, nec maximus libero. Nulla ut elementum mi. Nunc egestas vestibulum porta. Nam nisi enim, aliquam vel odio id, mollis suscipit mauris. Donec viverra congue sollicitudin. Duis euismod augue non erat vehicula, et ultricies mi malesuada. Morbi congue maximus velit. Praesent iaculis tempus purus vitae congue. Nullam sit amet volutpat sem, consectetur aliquam erat. Proin pellentesque lorem eget odio dapibus iaculis. Etiam tellus tortor, dignissim iaculis finibus vitae, luctus ut ante. Maecenas tempor non dolor a tincidunt. Sed varius condimentum lacus, id dignissim est congue a. Nulla rutrum, mi sit amet venenatis cursus, urna quam pellentesque metus, a tristique mauris odio a lorem.</em></p>
            <p><span style="background-color: #f1c40f;">Maecenas consectetur tellus eget imperdiet sagittis. Quisque erat magna, molestie sed semper id, auctor vel turpis. Donec luctus odio justo, vel rhoncus lorem elementum et. Maecenas placerat congue malesuada. Fusce efficitur quis orci ut semper. Donec vulputate nulla urna, non porta massa ullamcorper sit amet. Aenean vel dictum augue, sit amet fermentum lorem. Quisque felis felis, dapibus non fermentum in, fermentum ac sapien. Nulla facilisi. Nulla quam ante, scelerisque eu urna sit amet, fermentum pulvinar orci. Vestibulum pharetra leo orci, eu vehicula risus pellentesque vitae. Donec molestie tempus interdum. Pellentesque posuere dolor eu libero tempus suscipit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</span></p>
            </div>',
        ]);

        DB::table('posts')->insert([
            'title' => 'This is just a dummy title-9',
            'slug' => 'this-is-just-a-dummy-title-9',
            'category_id' => 5,
            'image'=>'https://source.unsplash.com/random/1920x1080',
            'excerpt'=>"This is just some sample data written here to fill the space...",
            'content'=>'<div id="lipsum">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer aliquet maximus odio. Curabitur vel massa eros. Nullam efficitur vestibulum eros, eu egestas diam tempor vitae. Maecenas ac auctor sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In porta, velit sit amet faucibus bibendum, massa dolor semper lorem, ut posuere nunc lacus ut nisi. Nam nisl lorem, iaculis eu odio id, aliquet facilisis arcu.</p>
            <p>Nullam a mauris turpis. Etiam faucibus est vel metus interdum lobortis finibus ornare erat. Nam vehicula quam mi, porta sagittis ligula malesuada sed. Nulla finibus scelerisque neque cursus laoreet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dapibus enim sed euismod ullamcorper. Duis at vulputate tellus. Proin ac purus eget ligula congue fermentum a in orci. Quisque fermentum elit at purus luctus, at pellentesque risus tincidunt. Nulla tincidunt nec est at consequat. Nullam nec dignissim leo. Maecenas condimentum et lorem eget viverra. Suspendisse pellentesque dui et massa aliquet, sed auctor dolor scelerisque. Morbi feugiat arcu a lacus rutrum posuere. Cras iaculis aliquet auctor. Nunc sagittis massa eget facilisis ullamcorper.</p>
            <p><strong>Nulla fermentum ex dui, vel aliquet mi auctor quis. Pellentesque cursus, nibh eu dapibus pulvinar, mi enim pellentesque elit, vel venenatis lacus metus et mi. Cras aliquam eu risus quis efficitur. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas congue eu urna vitae consectetur. Etiam sed risus auctor, porttitor ligula nec, auctor neque. Vivamus facilisis non dui nec ultrices. Curabitur magna sem, dignissim id dolor vel, tempor interdum erat. Maecenas et massa ut metus dictum cursus. Fusce mi tellus, viverra non nibh eleifend, elementum gravida eros. Etiam efficitur nulla a justo facilisis, non molestie tortor lobortis. Vestibulum aliquam mi in dolor pellentesque semper ac ac quam. Cras euismod egestas est, nec mattis metus fringilla quis. Curabitur aliquet libero non varius aliquam.</strong></p>
            <p><em>Quisque id erat vel enim scelerisque rutrum. Morbi vel nibh scelerisque, porta erat vel, sagittis risus. Vestibulum non malesuada ex, nec maximus libero. Nulla ut elementum mi. Nunc egestas vestibulum porta. Nam nisi enim, aliquam vel odio id, mollis suscipit mauris. Donec viverra congue sollicitudin. Duis euismod augue non erat vehicula, et ultricies mi malesuada. Morbi congue maximus velit. Praesent iaculis tempus purus vitae congue. Nullam sit amet volutpat sem, consectetur aliquam erat. Proin pellentesque lorem eget odio dapibus iaculis. Etiam tellus tortor, dignissim iaculis finibus vitae, luctus ut ante. Maecenas tempor non dolor a tincidunt. Sed varius condimentum lacus, id dignissim est congue a. Nulla rutrum, mi sit amet venenatis cursus, urna quam pellentesque metus, a tristique mauris odio a lorem.</em></p>
            <p><span style="background-color: #f1c40f;">Maecenas consectetur tellus eget imperdiet sagittis. Quisque erat magna, molestie sed semper id, auctor vel turpis. Donec luctus odio justo, vel rhoncus lorem elementum et. Maecenas placerat congue malesuada. Fusce efficitur quis orci ut semper. Donec vulputate nulla urna, non porta massa ullamcorper sit amet. Aenean vel dictum augue, sit amet fermentum lorem. Quisque felis felis, dapibus non fermentum in, fermentum ac sapien. Nulla facilisi. Nulla quam ante, scelerisque eu urna sit amet, fermentum pulvinar orci. Vestibulum pharetra leo orci, eu vehicula risus pellentesque vitae. Donec molestie tempus interdum. Pellentesque posuere dolor eu libero tempus suscipit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</span></p>
            </div>',
        ]);

        DB::table('posts')->insert([
            'title' => 'This is just a dummy title-10',
            'slug' => 'this-is-just-a-dummy-title-10',
            'category_id' => 1,
            'image'=>'https://source.unsplash.com/random/1920x1080',
            'excerpt'=>"This is just some sample data written here to fill the space...",
            'content'=>'<div id="lipsum">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer aliquet maximus odio. Curabitur vel massa eros. Nullam efficitur vestibulum eros, eu egestas diam tempor vitae. Maecenas ac auctor sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In porta, velit sit amet faucibus bibendum, massa dolor semper lorem, ut posuere nunc lacus ut nisi. Nam nisl lorem, iaculis eu odio id, aliquet facilisis arcu.</p>
            <p>Nullam a mauris turpis. Etiam faucibus est vel metus interdum lobortis finibus ornare erat. Nam vehicula quam mi, porta sagittis ligula malesuada sed. Nulla finibus scelerisque neque cursus laoreet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dapibus enim sed euismod ullamcorper. Duis at vulputate tellus. Proin ac purus eget ligula congue fermentum a in orci. Quisque fermentum elit at purus luctus, at pellentesque risus tincidunt. Nulla tincidunt nec est at consequat. Nullam nec dignissim leo. Maecenas condimentum et lorem eget viverra. Suspendisse pellentesque dui et massa aliquet, sed auctor dolor scelerisque. Morbi feugiat arcu a lacus rutrum posuere. Cras iaculis aliquet auctor. Nunc sagittis massa eget facilisis ullamcorper.</p>
            <p><strong>Nulla fermentum ex dui, vel aliquet mi auctor quis. Pellentesque cursus, nibh eu dapibus pulvinar, mi enim pellentesque elit, vel venenatis lacus metus et mi. Cras aliquam eu risus quis efficitur. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas congue eu urna vitae consectetur. Etiam sed risus auctor, porttitor ligula nec, auctor neque. Vivamus facilisis non dui nec ultrices. Curabitur magna sem, dignissim id dolor vel, tempor interdum erat. Maecenas et massa ut metus dictum cursus. Fusce mi tellus, viverra non nibh eleifend, elementum gravida eros. Etiam efficitur nulla a justo facilisis, non molestie tortor lobortis. Vestibulum aliquam mi in dolor pellentesque semper ac ac quam. Cras euismod egestas est, nec mattis metus fringilla quis. Curabitur aliquet libero non varius aliquam.</strong></p>
            <p><em>Quisque id erat vel enim scelerisque rutrum. Morbi vel nibh scelerisque, porta erat vel, sagittis risus. Vestibulum non malesuada ex, nec maximus libero. Nulla ut elementum mi. Nunc egestas vestibulum porta. Nam nisi enim, aliquam vel odio id, mollis suscipit mauris. Donec viverra congue sollicitudin. Duis euismod augue non erat vehicula, et ultricies mi malesuada. Morbi congue maximus velit. Praesent iaculis tempus purus vitae congue. Nullam sit amet volutpat sem, consectetur aliquam erat. Proin pellentesque lorem eget odio dapibus iaculis. Etiam tellus tortor, dignissim iaculis finibus vitae, luctus ut ante. Maecenas tempor non dolor a tincidunt. Sed varius condimentum lacus, id dignissim est congue a. Nulla rutrum, mi sit amet venenatis cursus, urna quam pellentesque metus, a tristique mauris odio a lorem.</em></p>
            <p><span style="background-color: #f1c40f;">Maecenas consectetur tellus eget imperdiet sagittis. Quisque erat magna, molestie sed semper id, auctor vel turpis. Donec luctus odio justo, vel rhoncus lorem elementum et. Maecenas placerat congue malesuada. Fusce efficitur quis orci ut semper. Donec vulputate nulla urna, non porta massa ullamcorper sit amet. Aenean vel dictum augue, sit amet fermentum lorem. Quisque felis felis, dapibus non fermentum in, fermentum ac sapien. Nulla facilisi. Nulla quam ante, scelerisque eu urna sit amet, fermentum pulvinar orci. Vestibulum pharetra leo orci, eu vehicula risus pellentesque vitae. Donec molestie tempus interdum. Pellentesque posuere dolor eu libero tempus suscipit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</span></p>
            </div>',
        ]);
    }
}
